### ISSUE TITLE
Why is ALDOA a contaminant?

### ISSUE THREAD

**Issue by Maithy15** [HaoGroup-ProtContLib/Protein-Contaminant-Libraries-for-DDA-and-DIA-Proteomics#1]
Hi,

I was trying out the Mouse tissue-specific contaminant database and got ALDOA as a contaminant. The samples are of mouse muscle, and I am wondering why ALDOs are considered contaminants as they are generally present in the muscle?

Thanks
Maithy

**Comment by HaoGroup** [comment]
Hi Maithy, 
Thanks for the question. ALDOA_Rabbit was labeled as a contaminant because it is a common antibody used in immune assays. The uniprot ID is P00883 labeled with a prefix of "Cont_". Mouse ALDOA has the same GeneID as Rabbit but different Uniprot ID. When you are filtering out the contaminant, use the "Cont_UniprotID", not the Gene ID. 

Another possibility is that some proteomics software has a function of marking contaminants for you. They may mark the contaminant based on GeneID, not uniprotID. This could be the reason because ALDOA_rabbit and ALDOA_mouse shared some protein sequences. 

Definitely examine the contaminant list before deleting them and make sure they have the "Cont_ "prefix in Uniprot ID. Hope this is helpful. Feel free to let us know if you have other questions. 
Sorry for the late reply. We just set up the Github notification function.

**Comment by Maithy15** [comment]
Hi,

Thanks for the reply! As you said, The problem was Rabbit and Mouse ALDOA has 98 % sequence identity and was grouped together. So when I removed proteins with the Cont prefix, the whole group got removed. As I am sure my sample does not have rabbit ALDOA I will just delete the Rabbit_ALDOA entry.

Thanks
Maithy
